# docker-compose.override.yml
version: "3.9"

networks:
  mib_net:            # user-defined network shared with redis‐server
    external: true    # it already exists – see the notes below

services:
  backend:
    build: ./backend
    env_file: .env
    container_name: app_supervision_mib_backend
    ports:
      - "5001:5001"
    environment:
      REDIS_HOST: redis-server      # hostname = existing container name
    networks:
      - mib_net

  gateway:
    build: ./api-gateway
    container_name: app_supervision_mib_gateway
    depends_on:
      - backend
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis-server
    networks:
      - mib_net

  frontend:
    build: ./frontend
    container_name: app_supervision_mib_frontend
    depends_on:
      - gateway
    ports:
      - "5002:5002"
    networks:
      - mib_net
