apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
  namespace: dev
data:
  # 1) El fichero .env completo
  .env: |-
    CASIMIR_ACCOUNT="CAXCL164"
    CASIMIR_PASSWORD="G/WnZ1n%LN#VYa"

    MIB_BASE="https://57.203.253.112:443"
    REDIS_HOST="redis"
    REDIS_PORT="6379"

  # 2) Claves individuales para que el Deployment las lea directamente
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MIB_BASE: "https://57.203.253.112:443"
  CASIMIR_ACCOUNT: "CAXCL164"
  CASIMIR_PASSWORD: "G/WnZ1n%LN#VYa"
