name: CI   # lint + build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ────────────────────────── LINT ──────────────────────────
  lint-dockerfiles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - api-gateway/Dockerfile
          - backend/Dockerfile
          - frontend/Dockerfile     # add more paths if you create new services
    steps:
      - uses: actions/checkout@v4

      - name: Hadolint ${{ matrix.file }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.file }}

  lint-python:
    runs-on: ubuntu-latest
    needs: lint-dockerfiles
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - run: pip install ruff==0.4.*
      - run: ruff .

  # ────────────────────────── BUILD ─────────────────────────
  build-images:
    needs: [lint-dockerfiles, lint-python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          tags: mib-gateway:ci
          push: false

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: mib-backend:ci
          push: false

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: mib-frontend:ci
          push: false
